title: Joyie Zhang
description: Data Engineer building AI-powered pipelines and standards to help data teams ship faster and adopt AI in production
theme: jekyll-theme-minimal

linkedin_username: joyie-zhang-7b8a5887
